force-app/main/default/objects/To_Do_List__c/To_Do_List__c.object-meta.xml
<CustomObject>
    <label>To Do List</label>
    <nameField>
        <label>To Do List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>To Do Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/To_Do_Task__c/To_Do_Task__c.object-meta.xml
<CustomObject>
    <label>To Do Task</label>
    <nameField>
        <label>To Do Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>To Do Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/To_Do_Task__c/fields/To_Do_List__c.field-meta.xml
<CustomField>
    <fullName>To_Do_List__c</fullName>
    <label>To Do List</label>
    <referenceTo>To_Do_List__c</referenceTo>
    <relationshipLabel>To Do Tasks</relationshipLabel>
    <relationshipName>To_Do_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_To_Do_List__c/User_To_Do_List__c.object-meta.xml
<CustomObject>
    <label>User To Do List</label>
    <nameField>
        <label>User To Do List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User To Do Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_To_Do_List__c/fields/To_Do_List__c.field-meta.xml
<CustomField>
    <fullName>To_Do_List__c</fullName>
    <label>To Do List</label>
    <referenceTo>To_Do_List__c</referenceTo>
    <relationshipLabel>User To Do Lists</relationshipLabel>
    <relationshipName>User_To_Do_Lists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_To_Do_List__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>User To Do Lists</relationshipLabel>
    <relationshipName>User_To_Do_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TaskManagerController.cls
public with sharing class TaskManagerController {

    @AuraEnabled
    public static List<ToDoListWithTasks> getUserToDoLists()
    {
        Set<Id> userSpecificTodoListIds = getUserSpecificTodoListIds();

        List<To_Do_List__c> todoLists = [SELECT Id, Name,
        (SELECT Id, Name FROM To_Do_Tasks__r)
        FROM To_Do_List__c
        WHERE Id IN :userSpecificTodoListIds];

        return wrapToDoLists(todoLists);
    }
    
    @AuraEnabled
    public static List<ToDoListWithTasks> wrapToDoLists(List<To_Do_List__c> todoLists)
    {
        List<ToDoListWithTasks> result = new List<ToDoListWithTasks>();

        for (To_Do_List__c eachList : todoLists)
        {
            ToDoListWithTasks todoList = new ToDoListWithTasks();
            todoList.listName = eachList.Name;
            todoList.listTasks = eachList.To_Do_Tasks__r;
            result.add(todoList);
        }

        return result;
    }

    private static Set<Id> getUserSpecificTodoListIds()
    {
        // Declarations
        Set<Id> result = new Set<Id>();
        Id userId = UserInfo.getUserId();

        // Get To Do Lists associated w/ logged in user
        List<User_To_Do_List__c> userTodoListsWithIds = [SELECT Id, To_Do_List__r.Id 
        FROM User_To_Do_List__c 
        WHERE User__c = :userId];

        // Extract Id for each To Do List
        for(User_To_Do_List__c eachUserTodoList : userTodoListsWithIds)
        {
            result.add(eachUserTodoList.To_Do_List__r.Id);
        }

        return result;
    }

    //Wrapper class for returning TDLists with associated TDTasks
    public class ToDoListWithTasks
    {
        @AuraEnabled
        public String listName;
        @AuraEnabled
        public List<To_Do_Task__c> listTasks;
    }
}