force-app/main/default/objects/To_Do_List__c/To_Do_List__c.object-meta.xml
<CustomObject>
    <label>To Do List</label>
    <nameField>
        <label>To Do List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>To Do Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/To_Do_Task__c/To_Do_Task__c.object-meta.xml
<CustomObject>
    <label>To Do Task</label>
    <nameField>
        <label>To Do Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>To Do Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/To_Do_Task__c/fields/To_Do_List__c.field-meta.xml
<CustomField>
    <fullName>To_Do_List__c</fullName>
    <label>To Do List</label>
    <referenceTo>To_Do_List__c</referenceTo>
    <relationshipLabel>To Do Tasks</relationshipLabel>
    <relationshipName>To_Do_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_To_Do_List__c/User_To_Do_List__c.object-meta.xml
<CustomObject>
    <label>User To Do List</label>
    <nameField>
        <label>User To Do List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User To Do Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_To_Do_List__c/fields/To_Do_List__c.field-meta.xml
<CustomField>
    <fullName>To_Do_List__c</fullName>
    <label>To Do List</label>
    <referenceTo>To_Do_List__c</referenceTo>
    <relationshipLabel>User To Do Lists</relationshipLabel>
    <relationshipName>User_To_Do_Lists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_To_Do_List__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>User To Do Lists</relationshipLabel>
    <relationshipName>User_To_Do_Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DummyDataGenerator.cls
public with sharing class DummyDataGenerator {

    /*
    public static List<ToDoListWithTasks> generateDummyTaskLists()
    {
        List<ToDoListWithTasks> result = new List<ToDoListWithTasks>();
        Id userId = UserInfo.getUserId();

        // Lists
        List<To_Do_List__c> todoLists = new List<To_Do_List__c>();
        todoLists.add(new To_Do_List__c(Name='List 1 BRO'));
        todoLists.add(new To_Do_List__c(Name='List 2 BRO'));

        // Tasks
        List<To_Do_Task__c> todoTasks = new List<To_Do_Task__c>();
        todoTasks.add(new To_Do_Task__c(Name='Task 1', To_Do_List__c=todoLists[0].id));
        todoTasks.add(new To_Do_Task__c(Name='Task 2', To_Do_List__c=todoLists[0].id));
        todoTasks.add(new To_Do_Task__c(Name='Task 3', To_Do_List__c=todoLists[0].id));
        todoTasks.add(new To_Do_Task__c(Name='Task 4', To_Do_List__c=todoLists[1].id));

        // Users To Do Lists
        List<User_To_Do_List__c> userLists = new List<User_To_Do_List__c>();
        userLists.add(new User_To_Do_List__c(Name='List1 Link', To_Do_List__c=todoLists[0].id, User__c=userId));
        userLists.add(new User_To_Do_List__c(Name='List2 Link', To_Do_List__c=todoLists[1].id, User__c=userId));

        JSONGenerator gen = JSON.createGenerator(true);

    }
    */
}